"""
Django settings for scope project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wa=5^%xaa=$r)5m%t*u)na&fif_$_wtdx^gpa_qh#&8nzoo)jc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "accounts",
    "videophotography",
    "dashboard",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'scope.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                 "dashboard.context_processors.notifications",
            ],
        },
    },
]

WSGI_APPLICATION = 'scope.wsgi.application'
AUTH_USER_MODEL = "accounts.User"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'videographyer_db',
        'USER': 'postgres',
        'PASSWORD': 'zxcvbnm,./',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField' 


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"







# ---------------------------------------------------------------------------
# Add these to your project's settings.py so send_mail() actually sends
# instead of just printing to the console (Django's default).
#
# Uses environment variables so you never commit real credentials.
# `pip install python-dotenv` (or django-environ) if you don't already
# have a way to load a .env file — the os.environ.get() calls below work
# with either.
# ---------------------------------------------------------------------------
import os

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")   # or your provider's SMTP host
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "davidogheneothuke42@gmail.com")           # e.g. yourteam@gmail.com
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "tsutajfseejupmcm")   # an app password, not your login password

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

# Where "New contact form message" notifications land. Defaults to
# DEFAULT_FROM_EMAIL if unset, but you'll usually want this to be a
# real team inbox (e.g. hello@scopeagreement.app).
CONTACT_INBOX_EMAIL = os.environ.get("CONTACT_INBOX_EMAIL", DEFAULT_FROM_EMAIL)

# ---------------------------------------------------------------------------
# .env (create this file at your project root, next to manage.py — and make
# sure it's in .gitignore, never commit it):
#
# EMAIL_HOST=smtp.gmail.com
# EMAIL_PORT=587
# EMAIL_HOST_USER=yourteam@gmail.com
# EMAIL_HOST_PASSWORD=your-16-char-app-password
# DEFAULT_FROM_EMAIL=yourteam@gmail.com
# CONTACT_INBOX_EMAIL=hello@scopeagreement.app
# ---------------------------------------------------------------------------
#
# Gmail specifically requires an "App password" (not your normal login
# password) — only available if 2-Step Verification is turned on:
# Google Account -> Security -> 2-Step Verification -> App passwords.
#
# Using a different provider (Zoho, Outlook, a custom domain host, SendGrid,
# Mailgun, etc.) — just swap EMAIL_HOST/EMAIL_PORT for theirs; the rest of
# this file and views_landing.py don't change.
#
# While developing, if you don't want to send real emails yet, swap the
# backend for this instead and messages will just print to your terminal:
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"