# Generated by Django 6.0.7 on 2026-07-31 15:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, default=0, help_text='Client rating from 0 to 5.', max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('in_progress', 'In Progress'), ('review', 'In Review'), ('revision', 'Awaiting Revisions'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='approved', max_length=30)),
                ('deliverables', models.TextField(blank=True)),
                ('revisions_included', models.PositiveIntegerField(default=2)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Project completion percentage.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_received', models.BooleanField(default=False)),
                ('deposit_received_at', models.DateTimeField(blank=True, null=True)),
                ('client_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='dashboard.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevisionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('included', 'Included in Package'), ('used', 'Used Revision'), ('billable', 'Extra Revision (Billable)'), ('completed', 'Completed')], default='included', max_length=20)),
                ('requested_by', models.CharField(blank=True, help_text='Client or videographer', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='dashboard.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
