# Generated by Django 6.0.7 on 2026-08-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='project_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
