# Generated by Django 6.0.7 on 2026-08-14 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_client_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first in filter bar')),
            ],
            options={
                'verbose_name_plural': 'Media categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video_file', 'Video (uploaded file)'), ('video_embed', 'Video (YouTube/Vimeo link)')], default='photo', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media_library/photos/%Y/%m/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='media_library/videos/%Y/%m/')),
                ('embed_url', models.URLField(blank=True, help_text='Full YouTube or Vimeo URL, e.g. https://youtu.be/abc123')),
                ('thumbnail', models.ImageField(blank=True, help_text='Required for videos. Optional for photos (falls back to the photo itself).', null=True, upload_to='media_library/thumbnails/%Y/%m/')),
                ('project_reference', models.CharField(blank=True, help_text="Optional — client/project name this media belongs to, e.g. 'Ade & Zara Wedding'.", max_length=150)),
                ('is_public', models.BooleanField(default=False, help_text="Only public items appear in the gallery. Keep off until you're ready to publish.")),
                ('is_featured', models.BooleanField(default=False, help_text='Featured items appear first / larger in the gallery.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='dashboard.mediacategory')),
            ],
            options={
                'ordering': ['-is_featured', '-uploaded_at'],
            },
        ),
    ]
