# Generated by Django 6.0.7 on 2026-08-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_mediacategory_mediaitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RevisionRequest',
        ),
    ]
