# Generated by Django 6.0.7 on 2026-08-15 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_delete_revisionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('included', 'Included in Package'), ('used', 'Used Revision'), ('billable', 'Extra Revision (Billable)'), ('completed', 'Completed')], default='included', max_length=20)),
                ('requested_by', models.CharField(blank=True, help_text='Client or videographer', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='dashboard.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
