# Generated by Django 6.0.7 on 2026-07-31 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Budget Range',
                'verbose_name_plural': 'Budget Ranges',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CoverageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Coverage Type',
                'verbose_name_plural': 'Coverage Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Delivery Deadline',
                'verbose_name_plural': 'Delivery Deadlines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepositOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Deposit Option',
                'verbose_name_plural': 'Deposit Options',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FinalLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Final Video Length',
                'verbose_name_plural': 'Final Video Lengths',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Project Type',
                'verbose_name_plural': 'Project Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RevisionRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Revision Round',
                'verbose_name_plural': 'Revision Rounds',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Admin Review'), ('approved', 'Approved by Admin'), ('proposal_sent', 'Proposal Sent to Client'), ('client_approved', 'Approved by Client'), ('rejected', 'Rejected')], default='pending', max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proposal_description', models.TextField(blank=True)),
                ('deliverables', models.TextField(blank=True)),
                ('timeline', models.TextField(blank=True)),
                ('revisions_included', models.PositiveIntegerField(default=2)),
                ('proposal_sent_at', models.DateTimeField(blank=True, null=True)),
                ('client_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_booking_requests', to=settings.AUTH_USER_MODEL)),
                ('videographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videographer_booking_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('project_description', models.TextField(blank=True)),
                ('coverage_ceremony', models.BooleanField(default=False)),
                ('coverage_speeches', models.BooleanField(default=False)),
                ('coverage_performances', models.BooleanField(default=False)),
                ('coverage_interviews', models.BooleanField(default=False)),
                ('coverage_product_shots', models.BooleanField(default=False)),
                ('coverage_drone_footage', models.BooleanField(default=False)),
                ('coverage_behind_the_scenes', models.BooleanField(default=False)),
                ('coverage_guest_reactions', models.BooleanField(default=False)),
                ('coverage_decoration', models.BooleanField(default=False)),
                ('coverage_social_media_content', models.BooleanField(default=False)),
                ('coverage_highlight_moments', models.BooleanField(default=False)),
                ('coverage_other', models.BooleanField(default=False)),
                ('special_requests', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('coverage_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('venue_name', models.CharField(max_length=255)),
                ('venue_address', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('maps_link', models.URLField(blank=True)),
                ('deliverable_highlight_video', models.BooleanField(default=False)),
                ('deliverable_full_event_video', models.BooleanField(default=False)),
                ('deliverable_social_reels', models.BooleanField(default=False)),
                ('deliverable_youtube_version', models.BooleanField(default=False)),
                ('deliverable_short_documentary', models.BooleanField(default=False)),
                ('deliverable_raw_footage', models.BooleanField(default=False)),
                ('deliverable_edited_photos', models.BooleanField(default=False)),
                ('deliverable_promo_trailer', models.BooleanField(default=False)),
                ('drone_coverage', models.BooleanField(default=False)),
                ('livestream', models.BooleanField(default=False)),
                ('extra_camera_operator', models.BooleanField(default=False)),
                ('photography', models.BooleanField(default=False)),
                ('same_day_edit', models.BooleanField(default=False)),
                ('teleprompter', models.BooleanField(default=False)),
                ('lighting_setup', models.BooleanField(default=False)),
                ('audio_recording', models.BooleanField(default=False)),
                ('subtitle_captions', models.BooleanField(default=False)),
                ('motion_graphics', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True)),
                ('confirm_information', models.BooleanField(default=False)),
                ('agree_booking_policy', models.BooleanField(default=False)),
                ('confirm_deposit_policy', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('proposal_sent', 'Proposal Sent'), ('client_approved', 'Client Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videophotography.budgetrange')),
                ('coverage_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videophotography.coveragetype')),
                ('deadline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videophotography.deliverydeadline')),
                ('delivery_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videophotography.deliverymethod')),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videophotography.depositoption')),
                ('final_length', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videophotography.finallength')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videophotography.paymentmethod')),
                ('project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videophotography.projecttype')),
                ('revision_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videophotography.revisionround')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
