# Generated by Django 5.2.7 on 2026-08-08 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videophotography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='deliverables',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='proposal_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='proposal_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='revisions_included',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='timeline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='videographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videographer_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
