# Generated by Django 6.0.7 on 2026-08-15 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videophotography', '0002_booking_approved_by_booking_deliverables_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text="Bootstrap icon class, e.g. 'bi-heart', 'bi-camera-reels'", max_length=50)),
                ('icon_bg', models.CharField(choices=[('bg-primary-soft', 'Primary'), ('bg-success-soft', 'Success'), ('bg-warning-soft', 'Warning'), ('bg-info-soft', 'Info'), ('bg-danger-soft', 'Danger')], default='bg-primary-soft', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_pill_text', models.CharField(default='Built for freelance videographers', max_length=100)),
                ('hero_title', models.CharField(default='Never argue over revisions again.', max_length=150)),
                ('hero_subtitle', models.TextField(default='Scope Agreement helps freelance videographers clearly define project scope, track revisions automatically, and keep every client on the same page.')),
                ('showcase_project_label', models.CharField(default='Active Project', max_length=50)),
                ('showcase_project_name', models.CharField(default='Ade & Kemi — Wedding Film', max_length=150)),
                ('showcase_status_label', models.CharField(default='On Track', max_length=50)),
                ('showcase_completion_percent', models.PositiveSmallIntegerField(default=72, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('showcase_revisions_used', models.PositiveSmallIntegerField(default=2)),
                ('showcase_revisions_total', models.PositiveSmallIntegerField(default=3)),
                ('showcase_due_text', models.CharField(default='Due in 9 days', max_length=50)),
                ('about_heading', models.CharField(default='Built by a videographer, for videographers', max_length=150)),
                ('about_paragraph_1', models.TextField(default='Scope Agreement started as a fix for my own frustration — endless "just one more tweak" requests, clients unclear on how many revisions were left, and revenue quietly slipping through the cracks. After years shooting weddings, corporate work, and music videos, I built the tool I wished I\'d had from day one: one place to set scope, track revisions, and get paid for the extra work.')),
                ('about_paragraph_2', models.TextField(default="Today it's used by videographers across Lagos, Johannesburg, and Accra to keep every project on track and every client on the same page.")),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='site_content/')),
                ('services_heading', models.CharField(default='What I render', max_length=100)),
                ('services_paragraph', models.TextField(default="From first consultation to final delivery, here's what I produce for clients — all managed through Scope Agreement so nothing gets lost along the way.")),
                ('testimonials_heading', models.CharField(default='What videographers are saying', max_length=100)),
                ('contact_heading', models.CharField(default='Talk to the team', max_length=100)),
                ('contact_paragraph', models.TextField(default="Questions about Scope Agreement, enterprise, or partnerships? Send us a message and we'll respond within one business day.")),
                ('contact_email', models.EmailField(default='hello@scopeagreement.app', max_length=254)),
                ('contact_phone', models.CharField(default='+234 803 000 0000', max_length=30)),
                ('contact_locations', models.CharField(default='Lagos · Johannesburg · Accra', help_text='Free text, shown as-is next to the location pin icon.', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site content',
                'verbose_name_plural': 'Site content',
            },
        ),
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videographers_count', models.PositiveIntegerField(default=0)),
                ('scopes_signed', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site stat',
                'verbose_name_plural': 'Site stats',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(help_text="e.g. 'Wedding Filmmaker, Lagos'", max_length=150)),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
    ]
