# Generated by Django 6.0.7 on 2026-08-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videophotography', '0003_contactmessage_service_sitecontent_sitestat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitestat',
            old_name='videographers_count',
            new_name='client_count',
        ),
    ]
