# Generated by Django 6.0.7 on 2026-08-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videophotography', '0004_rename_videographers_count_sitestat_client_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='about_image',
            field=models.FileField(blank=True, null=True, upload_to='site_content/'),
        ),
    ]
