# Generated by Django 6.0.7 on 2026-08-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videophotography', '0005_alter_sitecontent_about_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontent',
            name='about_image',
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_video',
            field=models.FileField(blank=True, help_text='MP4 (or other browser-supported video format) for the About section. Falls back to the default static video if empty and about_video_url is also empty.', null=True, upload_to='site_content/videos/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_video_poster',
            field=models.ImageField(blank=True, help_text='Poster image shown before the video plays / while it loads. Optional.', null=True, upload_to='site_content/video_posters/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_video_url',
            field=models.URLField(blank=True, help_text="Optional: link directly to a hosted video FILE (e.g. an .mp4 URL on S3/Cloudinary/etc). NOT a YouTube/Vimeo watch page link — those need an <iframe> embed, not a <video> tag, and aren't supported by this field. Takes priority over an uploaded about_video file if both are set."),
        ),
    ]
