# Generated by Django 6.0.7 on 2026-08-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videophotography', '0006_remove_sitecontent_about_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontent',
            name='about_video_url',
        ),
    ]
